### ISSUE TITLE
Commands are not recognized

### ISSUE THREAD

**Issue by Kraymer** [felipec/git-smartlist#1]
system: Mac OS X 10.11.6

~~~
❯ git clone https://github.com/felipec/git-smartlist.git
Cloning into 'git-smartlist'...
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 93 (delta 46), reused 86 (delta 39), pack-reused 0
Unpacking objects: 100% (93/93), done.

❯ cd git-smartlist

❯ ./git-smartlist all
Unknown command ''
usage: git-smartlist <action>

Action
    specific [<branches>]
    all
    branches [<branches>]
    from [<branch>] [<from>]
    from-upstream [<branch>] [<default>]
    negate-upstreams <branches>

~~~

**Comment by felipec** [comment]
The usage help is wrong, the command should be `git smartlist echo all` if you just want to display the output, or `git smarlist log all` if you actually want to run the real command.

I've fixed that in commit 6ac28ca.

**Comment by Kraymer** [comment]
Thanks, still does not work though.

~~~
❯ ./git-smartlist echo all
error: unknown option `type=bool'
usage: git config [<options>]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --get-urlmatch        get value specific for the URL: section[.var] URL
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 add a new variable: name value
    --unset               remove a variable: name [value-regex]
    --unset-all           remove all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            open an editor
    --get-color           find the color configured: slot [default]
    --get-colorbool       find the color setting: slot [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte
    --name-only           show variable names only
    --includes            respect include directives on lookup
    --show-origin         show origin of config (file, standard input, blob, command line)

error: unknown option `type=bool'
usage: git config [<options>]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --get-urlmatch        get value specific for the URL: section[.var] URL
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 add a new variable: name value
    --unset               remove a variable: name [value-regex]
    --unset-all           remove all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            open an editor
    --get-color           find the color configured: slot [default]
    --get-colorbool       find the color setting: slot [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte
    --name-only           show variable names only
    --includes            respect include directives on lookup
    --show-origin         show origin of config (file, standard input, blob, command line)

--branches --remotes --not 6ac28cacdf0eaa59bd75e4129a598d2ce0d2ae4e
~~~

**Comment by felipec** [comment]
@Kraymer Hmmm. What version of git are you using?

**Comment by Kraymer** [comment]
@felipec 

~~~
❯ git --version
git version 2.14.1
~~~

**Comment by felipec** [comment]
All right. I was using an option that wasn't available until git 2.18, now it should be fixed: 3877663.

**Comment by felipec** [comment]
Not sure why I didn't close this.
